/**
 * Assemble a repo's files into one agent-ready context blob, with clear file
 * headers and a token budget so an agent can request "at most N tokens".
 */

import type { RepoBundle, RepoFile } from './github';

export interface PackResult {
  text: string;
  tokens: number;
  files: number;
  totalFiles: number;
  truncated: boolean;
}

export interface PackOptions {
  maxTokens?: number;
}

/**
 * Rough GPT-style token estimate. Deterministic and dependency-free: ~4
 * characters per token is the widely-used heuristic. Labelled an estimate.
 */
export function estimateTokens(text: string): number {
  return Math.ceil(text.length / 4);
}

function fileSection(file: RepoFile): string {
  return `\n==== ${file.path} ====\n${file.text.replace(/\s+$/, '')}\n`;
}

export function packRepo(bundle: RepoBundle, opts: PackOptions = {}): PackResult {
  const budget = typeof opts.maxTokens === 'number' && opts.maxTokens > 0 ? Math.floor(opts.maxTokens) : Infinity;

  const header =
    `# Repository: ${bundle.slug}@${bundle.ref}\n` +
    `# Files: ${bundle.files.length}\n` +
    `# Generated by ctx.vanshul.com — agent-ready context\n`;

  let text = header;
  let tokens = estimateTokens(header);
  let included = 0;
  let truncated = bundle.truncated;

  for (const file of bundle.files) {
    const section = fileSection(file);
    const cost = estimateTokens(section);
    if (included > 0 && tokens + cost > budget) {
      truncated = true;
      break;
    }
    text += section;
    tokens += cost;
    included++;
  }

  return { text, tokens, files: included, totalFiles: bundle.files.length, truncated };
}
