/**
 * Assemble a repo's files into one agent-ready context blob, with clear file
 * headers and a token budget so an agent can request "at most N tokens".
 */

import type { RepoBundle, RepoFile } from './github';

export interface PackResult {
  text: string;
  tokens: number;
  files: number;
  totalFiles: number;
  truncated: boolean;
}

export interface PackOptions {
  maxTokens?: number;
}

/**
 * Rough GPT-style token estimate. Deterministic and dependency-free: ~4
 * characters per token is the widely-used heuristic. Labelled an estimate.
 */
export function estimateTokens(text: string): number {
  return Math.ceil(text.length / 4);
}

function fileSection(file: RepoFile): string {
  return `\n==== ${file.path} ====\n${file.text.replace(/\s+$/, '')}\n`;
}

export function packRepo(bundle: RepoBundle, opts: PackOptions = {}): PackResult {
  const budget = typeof opts.maxTokens === 'number' && opts.maxTokens > 0 ? Math.floor(opts.maxTokens) : Infinity;

  // Select files greedily under the token budget (always keep at least one).
  const included: RepoFile[] = [];
  let sectionTokens = 0;
  let truncated = bundle.truncated;
  for (const file of bundle.files) {
    const cost = estimateTokens(fileSection(file));
    if (included.length > 0 && sectionTokens + cost > budget) {
      truncated = true;
      break;
    }
    included.push(file);
    sectionTokens += cost;
  }

  const manifest = included.length
    ? `# Files (${included.length}${truncated ? ` of ${bundle.files.length}` : ''}):\n` +
      included.map((f) => `#   ${f.path}`).join('\n') + '\n'
    : '';
  const header =
    `# Repository: ${bundle.slug}@${bundle.ref}\n` +
    `# Generated by ctx.vanshul.com — agent-ready context\n` +
    manifest;

  const text = header + included.map(fileSection).join('');
  return { text, tokens: estimateTokens(text), files: included.length, totalFiles: bundle.files.length, truncated };
}
